### PR TITLE
HUE-9538 [core] user home directories are not created for Newly Logged in User

### PR DESCRIPTION
**Pull request by Akhilsnaik**
**What changes were proposed in this pull request?**
HUE-9538 [core] user home directories are not created for Newly Logged in User

**How was this patch tested?**

Tested manually in master branch, if once code change is pushed, user home directory will be created for newly logged in user i LDAP

```
[30/Oct/2020 04:21:34 -0700] backend      DEBUG    Creating Django user user106
[30/Oct/2020 04:21:34 -0700] backend      DEBUG    Populating Django user user106
[30/Oct/2020 04:21:35 -0700] resource     DEBUG    GET http://asnaikCdp01.example.com:9870/webhdfs/v1 returned in 0ms
[30/Oct/2020 04:21:35 -0700] resource     DEBUG    PUT None http://asnaikCdp01.example.com:9870/webhdfs/v1//user/user106?permission=0755&op=MKDIRS&user.name=hue&doas=hdfs  returned in 8ms 200 16 {"boolean":true}
```

### CODE REVIEW

**Comment by Akhilsnaik** [comment]
@romainr  could you please help me review this, related to this commit : https://github.com/cloudera/hue/commit/7a251eb79643bfe6f17e068a4fbb32781f63b2bb#diff-ef335bb925563195b9144aa3a2953deb567d467510afbf123f54c304a7f413cdR133

**Comment by romainr** [comment]
Nice one!

This is a legit fix, previous commit was removing the request.fs of non authenticated users (as they could access the fs...) and here you set the request.fs in the post authentication (which happens after the middleware)

**Comment by romainr** [comment]
And we should add some unit tests at some point (with Mock Fs)

**Comment by romainr** [comment]
+1 to ship

**Pull request merged**
