### PR TITLE
Add scalatra-metrics support to livy

### PR DESCRIPTION
**Pull request by jmelching**
Mount MetricsAdminServlet under "/" which gives 4 new contexts: /healthcheck, /metrics, /ping, and /threads

 The admin servlet also gives a small html page with links to the above.  Additional metrics and checks can be added easily in the future.

### CODE REVIEW

**Comment by jmelching** [comment]
I have tried to sign the EULA but it the site containing it isn't working.

**Comment by romainr** [comment]
Thanks! Erick is going to have a look!

BTW for the CCL if needed there is the online form that might be easier: https://github.com/cloudera/hue/wiki/Ccla#online-form

**Comment by erickt** [comment]
Looks great! Once the CCL is signed I'll merge it in!

**Comment by romainr** [comment]
Let's merge it and the form is https://docs.google.com/a/cloudera.com/forms/d/1DVn3B5_fntw0QByIOq8TsAUnz32noAy-wYS7hq6le5M/viewform

**Pull request merged**
