### PR TITLE
#1683 - update live parsers demo with latest parsers

### PR DESCRIPTION
**Pull request by Akhilsnaik**
**What changes were proposed in this pull request?**
#1683 - update live parsers demo with latest parsers

**How was this patch tested?**
-- Tested by running the `npm run test` and also make sure the parsers are updated from `hue/npm_dist/lib/parsers` folder .

### CODE REVIEW

**Comment by romainr** [comment]
BTW, was it done manually? (gen in Hue, then copy paste to the dist)

I did not see the info in https://docs.gethue.com/developer/development/#documentation-1
(probably at least putting the shell commands)

**Comment by Akhilsnaik** [comment]
> BTW, was it done manually? (gen in Hue, then copy paste to the dist)
> 
> I did not see the info in https://docs.gethue.com/developer/development/#documentation-1
> (probably at least putting the shell commands)

i will raise an new PR for updating the docs tommorow. merging this now.

**Comment by jkillian** [comment]
Hi @Akhilsnaik, just curious, did documentation for this get added eventually? I looked for it but may have missed it. 

I've been using these static files in a project of mine (instead of the NPM package, for various reasons, but mostly because the NPM package requires a bunch of dependencies I want to avoid installing). I'd love to know how to rebuild them so that I can contribute a PR that updates the docs site. (Some fixes went in in #2185 that I'm keen to try out!)

**Comment by jkillian** [comment]
Fwiw, I think I figured out the steps I needed to get the build parsers (written from the perspective of someone who has never cloned the repo):

1) `git clone git@github.com:cloudera/hue.git`
2) `cd hue`
3) `npm install`
4) `cd tools/jison`
5) `node generateParsers.js genericAutocomp` (or whatever parsers you care about)
6) `cd ../..`
7) `npm run webpack-npm`
8) Built parsers are in `npm_dist/lib/parsers/`

**Pull request merged**
