### PR TITLE
[python3.9] Upgrading greenlet and sasl as old versions are not compatible with py39

### PR DESCRIPTION
**Pull request by agl29**
## What changes were proposed in this pull request?

- greenlet==0.4.15 => greenlet==2.0.2
- sasl==0.2.1 => sasl==0.3.1

## How was this patch tested?

- Created a canary and build a jenkins cluster with that GBN (python3.8)
- Hue is running fine.
- All the basic functions are checked

### CODE REVIEW

**Comment by agl29** [comment]
@amitsrivastava @wing2fly  @ranade1 
Please let me know what more test we can do?
Hive and Impala queries are also running fine after upgrading the sasl lib.
And as cluster is running fine and we can do all the basic operations. If anything left and we need to take a look please let me know.

**Comment by agl29** [comment]
> Why greenlet and sasl related to Python 3.9? If there is any documentation, please add it in the PR description. Or if this is the finding in the test result, share the exception/error message.

For greenlet -> https://greenlet.readthedocs.io/en/stable/changes.html#id11
Support for python3.9 started from greenlet==0.4.16

For sasl ->  https://github.com/cloudera/python-sasl/commit/a754f7e7ba9904a01f53aa39bafff36b8851c530
Support for python3.9 added in sasl==0.3.1 (read the description of the mentioned commit)

@wing2fly

**Review by wing2fly — APPROVED** [review]

**Review by JohanAhlen — APPROVED** [review]
LGTM!

**Review by ranade1 — APPROVED** [review]
Looks good.

**Pull request merged**
