### PR TITLE
update pyopenssl to 0.15.1

### PR DESCRIPTION
**Pull request by oflebbe**
hue does not support TLS1.2, the only "secure" https:// protocol today.

pyopenssl 0.13 is the culprit.
pyopenssl 0.15.1 does, since support for it was added in 0.14 (see for instance https://github.com/pyca/pyopenssl/releases)

With this patch one can configure hue to support tls1.2 with AES256-GCM-SHA384 in hue.ini for instance with

ssl_cipher_list=HIGH:!aNULL:!MD5:!kEXDH:!kECDH:!DSS:!ECDSA

As a sideeffect one needs to include the python modules pycparser, cryptography, cffi
And one gets a new dependency on libffi-dev on deb, libffi-devel on rpm systems.

### CODE REVIEW

**Comment by oflebbe** [comment]
BTW. This patch is rather large, only  containing unmodified upstream sources of pyopenssl, pycparser, cryptography, cffi

**Comment by romainr** [comment]
Nice one! We are about to cut 3.10 so will go back to see one just after (because of new package dependencies)

**Comment by oflebbe** [comment]
Thanks! 

Since I tripped over this problem a few times:
At seemingly random times the __init__.py in `desktop/core/ext-py/cryptography-1.1.1/src/_cffi_src` is missing.  Do not know if my jenkins, git, patch or some phase of the moon is triggering it: 

If you trip over "ImportError: No module named _cffi_src.utils" please make sure it is properly checked in. (maybe just add a comment into this file)

**Comment by romainr** [comment]
One question, we tested with current master and it seems to support TLS1.2 already.
Is 0.15 required for using AES256-GCM-SHA384?

`Here's what I see from openssl s_client:


# openssl s_client -connect nightly-kerberized-1.gce.cloudera.com:8888
CONNECTED(00000003)
depth=0 O = Hadoop, CN = nightly-kerberized-1.gce.cloudera.com
verify error:num=18:self signed certificate
verify return:1
depth=0 O = Hadoop, CN = nightly-kerberized-1.gce.cloudera.com
verify return:1
---
Certificate chain
 0 s:/O=Hadoop/CN=nightly-kerberized-1.gce.cloudera.com
   i:/O=Hadoop/CN=nightly-kerberized-1.gce.cloudera.com
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDITCCAgmgAwIBAgIEGKVtaDANBgkqhkiG9w0BAQsFADBBMQ8wDQYDVQQKEwZI
YWRvb3AxLjAsBgNVBAMTJW5pZ2h0bHkta2VyYmVyaXplZC0xLmdjZS5jbG91ZGVy
YS5jb20wHhcNMTYwMzExMTcxOTMwWhcNMjEwMzEwMTcxOTMwWjBBMQ8wDQYDVQQK
EwZIYWRvb3AxLjAsBgNVBAMTJW5pZ2h0bHkta2VyYmVyaXplZC0xLmdjZS5jbG91
ZGVyYS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCuMre/B2hU
PaiqdAPQJer6mbzmB257GCCBoYb0U7poDgIQMWFfTmO0jJg8iZRAEG7ZtaWI+JFB
XJmddEreZ6v4bUbYVLVCvVGex9gbV2BqfuJC32/W9vvWmM1oHnPxlNXriNFri7k4
0joavujYimUXg8gJtytydWwm5GWMzl1pvTlRO4lplsy1wO30hMM+uOkHawW7WoyX
B752qK6p74XJrUJQnyCCpsqY5yBZlKbkz8mNHvIOX1WS3ytDGEm2RQsMTBIVeI01
qyrRA6XmDPHREUD+5Bc4QCMnMBOAP7RhWdZrK2uM93wJC1RveHzBOvaVe1NJlBL2
FAg1WiuAGqmTAgMBAAGjITAfMB0GA1UdDgQWBBQZkDujKjhs/Tl6Av+y2Unf/AC7
hzANBgkqhkiG9w0BAQsFAAOCAQEAP8cVCuDnpNnpZonv6yj7jpLYaaUaf7av/WIQ
zPJe3bNuiyEVAPPAWVUBY12phSff7p1+A2xx6wThgEF1CjmBtBKJ2d53xuWPMQNq
eaz93IPIjtSGSZ8JVW2rGWKTIoM8YMl8WmS3RcQ583koIqTzUpLPQGaX4ekSTyeo
kyU8dx6+qbsPaYyuDvGHhzBk9X6lK5Lzj/qXycfdhdrCzG10mSp+c35Pppc5FvC4
xUaTgtpoTT/yGjcPOnOM2hUuC+byfArqEuL6uM0PoJ4UJNa8BgSzRgFI+sDHcNZQ
MiOM9osZuSDrxe9VY7A09m3BfG72TvtK/pnRwS7jjP90gWYGfQ==
-----END CERTIFICATE-----
subject=/O=Hadoop/CN=nightly-kerberized-1.gce.cloudera.com
issuer=/O=Hadoop/CN=nightly-kerberized-1.gce.cloudera.com
---
No client certificate CA names sent
---
SSL handshake has read 1118 bytes and written 565 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES256-GCM-SHA384
    Session-ID: F30BB28E53EA977567A16F469844389DD42159D14D4B3E04B4DA62B4F09CC3A6
    Session-ID-ctx: 
    Master-Key: BA23C387805D45E383841BAE7DA485AC5ADA16C8D542F491F21177A0C86DFF47EE1920F4B1134E26CDB0E7CA8C4AF375
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - e3 be 4c 4e 8f 60 e6 18-dc d4 74 c7 3a 8f 96 d0   ..LN.`....t.:...
    0010 - 67 86 06 6d b7 5b 57 36-5c 3b c3 48 4f fc ed a5   g..m.[W6\;.HO...
    0020 - a4 e7 6a 7f a4 8e 8e 9d-bf 0b fd fc 5d b5 2e 9c   ..j.........]...
    0030 - 16 5e ed 9d 4c c8 b3 37-47 4a 6a 55 bb 3c d7 d6   .^..L..7GJjU.<..
    0040 - e5 ca 06 5c b5 1f 8d 5f-8f a5 5f 82 81 04 94 32   ...\..._.._....2
    0050 - 88 60 01 f2 52 51 1d 5f-e7 67 55 48 7a 1d d5 d4   .`..RQ._.gUHz...
    0060 - ee 49 0a 8f 7b 57 a8 e0-05 77 b3 39 fd db 8d 2e   .I..{W...w.9....
    0070 - 31 b8 ca 66 e1 c0 9c 8b-a3 13 28 f7 52 54 62 93   1..f......(.RTb.
    0080 - d6 c4 1b 0d 81 b5 b3 3a-c9 07 6a 41 1a f7 2f 19   .......:..jA../.
    0090 - 5a 51 30 9a 7b b4 7e df-36 55 bf 4d b3 ef 66 3d   ZQ0.{.~.6U.M..f=

    Start Time: 1457734167
    Timeout   : 300 (sec)
    Verify return code: 18 (self signed certificate)
---`

**Comment by oflebbe** [comment]
I have no idea why you see a TLSv1.2 with current master.

TLSv1.2 did not work for us in the Bigtop 1.0.0 (and 1.1.0) release. Fact is that the 0.14 Release Notes of pyopenssl does mention that it supports 
{code}
2013-10-06  Jean-Paul Calderone  <exarkun@twistedmatrix.com>

	* OpenSSL/ssl/context.c: Add support for negotiating TLS v1.1 or
	  v1.2.
{code} and hue has 0.13. The hue pyopenssl is missing the TLSv1.2 constants, it is a complete mystery to me, how you can get TLSv1.2.

May I ask you if your  {{nightly-kerberized-1.gce.cloudera.com}} system uses an apache server with mod_wsgi rather than the cherrypi server?

May I ask on which OS (on the server side) you did the test?

**Comment by michaelweiser** [comment]
I'm the one who initially looked into TLSv1.2 support in hue for Olaf. It seems I miscommunicated a distinction I made between "supporting TLSv1.2" and "supporting *accepting only* TLSv1.2":

Our actual requirement is to be able to disable old SSL/TLS versions hue. Since hue has no configuration option for that, I looked into the code and found that it initialises the SSL context with ``SSLv23_METHOD`` in ``wsgiserver.py``. With current OpenSSL this does indeed include TLSv1.1 and 1.2 but it also includes SSLv3 (and potentially v2) which we wanted to get rid of. When trying to replace that with ``TLSv1_2_METHOD`` I found that the underlying pyOpenSSL did not support it. So before even trying to implement an SSL/TLS protocol selection configuration option in hue we need an updated pyOpenSSL that supports selection of all current TLS versions.

Due to above miscommunication we do not currently have a patch that adds the actual protocol configuration option but we'd certainly be willing to give it a go if there's a consensus that it is the way to go.

**Comment by oflebbe** [comment]
To summarize: hue current master does support TLSv1.2 and disables SSLv3 out of the box. But it has no means to disable TLSv1.1 and TLSv1 , which is desirable in certain environments. 

The patch enables Hue to switch off TLSv1.1 and lower but does not actually do it.

So you are safe to leave it out from a soon-to-be-released version, But I would like to encourage you to upgrade pyopenssl in master in order to have the groundwork ready to make ciphers properly configurable .

Thanks and sorry for the confusion on my side.

**Comment by romainr** [comment]
Thanks a lot for the patch and all the clarifications, this is appreciated!

If you plan to have a patch to limit the old TLS versions, feel free to send it. This is indeed becoming a must do in many environment.

**Pull request merged**
