### PR TITLE
[ci] Adding autoclose stale PRs/Issues

### PR DESCRIPTION
**Pull request by romainr**
WIP

Need to add some labels to prevent blind closure of everything and the legit issues, e.g. 'roadmap' for example or 'triaged'

Will see for getting (lighter) workflow from https://github.com/kubernetes/kubernetes/issues

### CODE REVIEW

**Comment by wing2fly** [comment]
nice idea!

**Comment by romainr** [comment]
Current plan: keep it simple, 'accepted' tagged items won't be auto close

Open to debate!

**Review by wing2fly — APPROVED** [review]
LGTM

**Comment by romainr** [comment]
To add: skip closing issues linked to Project/Milestones

**Pull request merged**
