### PR TITLE
HUE-7182 Accented characters not inserted correctly in editor

### PR DESCRIPTION
**Pull request by todaychi**
link ace_issue_3027
link ace_issue_3045 
link ace_issue_3097 
link ace_issue_3100 
link ace_issue_3249

### CODE REVIEW

**Comment by romainr** [comment]
Thanks!

Are you also trying to get this contributed back to upstream Ace?

**Comment by enricoberti** [comment]
@romainr  
It's actually this
https://github.com/ajaxorg/ace/commit/87401ca017ead03aa0cc7f89d295af03fa32b32c
plus this
https://github.com/ajaxorg/ace/commit/1667af1a3a2ae0bbfc39ae4f2ac429e673217641
(but missing one line)
and also this is missing
https://github.com/ajaxorg/ace/commit/949044ecb6a6f7bfd56291ca353cff99199892ff

It's probably easier for us to just import the new textinput.js plus the other minor fix

**Comment by todaychi** [comment]
@enricoberti 
Thanks for your advice, the new textinput.js seems to be fine in hue editor ;

**Comment by romainr** [comment]
Pushed in
https://issues.cloudera.org/browse/HUE-7182

**Pull request closed without merging**
