### PR TITLE
[Livy] Session property "files" not work

### PR DESCRIPTION
**Pull request by sky4star**
Fix issue #323 
I made a little change on Livy side to parse values of files and jars correctly.

### CODE REVIEW

**Comment by romainr** [comment]
Nice!

Would you mind signing the legal contributor list?
https://github.com/cloudera/hue/wiki/Ccla#online-form

And since Livy actually moved out of Hue (the project got pretty popular), maybe check on
https://github.com/cloudera/livy
if your fix is there!

**Comment by sky4star** [comment]
Thanks for the information, romainr.
I have signed and i will submit the pull request there.

**Comment by romainr** [comment]
There is no problem if you want to also have this commit in Hue, we will remove the original Livy project from Hue in Hue 4 and rely entirely on https://github.com/cloudera/livy afterwards

**Comment by sky4star** [comment]
I see. Since the next release (3.10) will still use the original Livy, please merge this commit into Hue. 
Thanks.

**Comment by romainr** [comment]
No problem!

Just do you think you could get rid of the two merge commits in the pull request? (the gitub history will be cleaner this way)
 @sky4star	Merge remote-tracking branch 'cloudera/master'	07a6460
 @sky4star	Merge remote-tracking branch 'cloudera/master'

**Comment by sky4star** [comment]
Sure, it makes sense. It was my mistake to bring meaningless merging commits here.
But i don't know how to clean up current pull request. So i just closed this one and created a new one. Sorry for the inconvenience caused.
Please take a look at #334

**Pull request closed without merging**
