### PR TITLE
[Dajngo 4.0 Warning] RemovedInDjango40Warning: django.utils.translati…

### PR DESCRIPTION
**Pull request by agl29**
…on.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy()

## What changes were proposed in this pull request?

- ugettext_lazy -> gettext_lazy and ugettext -> gettext
## How was this patch tested?

- https://docs.djangoproject.com/en/1.11/_modules/django/utils/translation/
- https://docs.djangoproject.com/en/3.1/internals/deprecation/
- https://docs.djangoproject.com/en/3.0/_modules/django/utils/translation/

### CODE REVIEW

**Comment by agl29** [comment]
Can we use [autopep8 ](https://github.com/hhatto/autopep8) to automate or for suggestions?
Otherwise will do it one by one (will take some time)

**Review by romainr — APPROVED** [review]
Those are just aliases right?

**Comment by agl29** [comment]
> Those are just aliases right?

not getting

**Comment by romainr** [comment]
What is the difference between both functions?

**Comment by romainr** [comment]
If with Django 1 it is not equal, we need to keep it the same, and import the new function only with Python 3 so

**Comment by agl29** [comment]
I have added the flag
```
if sys.version_info[0] > 2:
  from django.utils.translation import gettext as _
else:
  from django.utils.translation import ugettext as _
```
and added `import sys` in approximately all the modified files.
Please go through the changes once if possible.

**Review by romainr — APPROVED** [review]
You are a regexp pro now :)

**Pull request merged**
