### PR TITLE
[frontend] Dismiss info alert popup messages after 3 seconds (along with Unit Test)

### PR DESCRIPTION
**Pull request by ananya-agarwal**
## What changes were proposed in this pull request?
The info alert popup messages will automatically go after 3 seconds from when it is shown. Since, the error and warning messages are important and we want the user to close them themselves, so such a timer is only used for the info messages.

## How was this patch tested?
Attached a demo video. 
The patch is manually tested on the Hue UI using a stopwatch of 3 seconds.

https://github.com/cloudera/hue/assets/68558847/c1610f97-0ad8-48a9-bd79-ef9a8892b933

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

### CODE REVIEW

**Review by JohanAhlen — APPROVED** [review]
Nice!

**Review by bjornalm — CHANGES_REQUESTED** [review]
Nice! Lets also add a unit test for this like we discussed in yesterdays meeting. Was 3 seconds the time span used for the old messages? It seems a bit short but perhaps it is ok.

**Comment by ananya-agarwal** [comment]
Regarding the timer earlier: Checked it during 1-1 with Johan. It was 3 seconds earlier too. We can do it whatever we feel is better.
Regarding the unit case: I will add it today. 
PFA
Earlier3000
UnitTest_TimerInfo

**Comment by ananya-agarwal** [comment]
Bjorn, can you please have a look now? are we good to merge it now?

**Review by bjornalm — APPROVED** [review]
Great work

**Pull request merged**
