### PR TITLE
CircleCI: Bump version to 2.1

### PR DESCRIPTION
**Pull request by martin-g**
## What changes were proposed in this pull request?

This is the first part of https://github.com/cloudera/hue/pull/2531

This PR changes the version of CircleCI config from `2.0` to `2.1`. This is needed to be able to use [reusable config](https://circleci.com/docs/2.0/reusing-config/) functionality in the next PR.
`2.1` does not allow usage of `.` (dot) in the job names.

## How was this patch tested?

Only CircleCI's config.yml has been modified. CircleCI jobs should still work!

### CODE REVIEW

**Review by romainr — APPROVED** [review]
Nice, thanks!

(and could we can keep the numbers)

**Comment by martin-g** [comment]
> (and could we can keep the numbers)

Yes, it seems I misread the regex in the error the first time.

**Review by romainr — APPROVED** [review]

**Comment by romainr** [comment]
Not sure why "ci/circleci: build-py3.6 Expected — Waiting for status to be reported" is stuck

**Comment by romainr** [comment]
--> renamed GH check to "ci/circleci: build-py-36"

**Pull request merged**
