### PR TITLE
Fixed NoneType Error

### PR DESCRIPTION
**Pull request by cgkbfrd**
The problem `AttributeError: 'Nonetype' object has not attribute 'update'` was throwed when I execute query with HS2, Maybe we should ensure the attribute "properties" is not "none", thus I add the empty dict to replace 'Nonetype' if the properties is none.

### CODE REVIEW

**Comment by cgkbfrd** [comment]
The problem `AttributeError: 'Nonetype' object has not attribute 'update'` was throwed when I execute query with HS2, Maybe we should ensure the attribute "properties" is not "none", thus I add the empty dict to replace 'Nonetype' if the properties is none.

**Comment by cgkbfrd** [comment]
The problem AttributeError: 'Nonetype' object has not attribute 'update' was throwed when I execute query with HS2, Maybe we should ensure the attribute "properties" is not "none", thus I add the empty dict to replace 'Nonetype' if the properties is none.

**Review by ranade1 — APPROVED** [review]
Looks good

**Review by Harshg999 — APPROVED** [review]

**Comment by Harshg999** [comment]
@cgkbfrd Can you rebase your PR?

**Comment by cgkbfrd** [comment]
> @cgkbfrd Can you rebase your PR with master?

thanks, I  have make rebase.

**Comment by Harshg999** [comment]
Strange, I am not getting an option to merge the PR.

**Comment by Harshg999** [comment]
@quadoss @ranade1 @wing2fly Are you able to merge this PR? All checks are green.

**Comment by ranade1** [comment]
recheck

**Review by quadoss — APPROVED** [review]

**Pull request closed without merging**
