### PR TITLE
Using multiple webhdfs urls in hue.ini 

### PR DESCRIPTION
**Pull request by miho120**
Problem:
You can specify only one webhdfs url in hue.ini. And when name node with webhdfs (what is specified in hue.ini webhdfs_url) goes to standby state you will have an error in File Browser "Operation category READ is not supported in state standby (error 403)". 
Solution:
With this you are able to set up multiple webhdfs urls in hue.ini. HUE will use first webhdfs url and in case of error second webhdfs url.
Example of configuration in hue.ini that you can use with this patch:
webhdfs_url=http://namenodewebhost1:port/webhdfs/v1, http://namenodewebhost2:port/webhdfs/v1

And with this hue is going to be more HA.

### CODE REVIEW

**Comment by nbonavia** [comment]
I have exactly the same issue. It would be awesome if you can address this problem.

**Comment by romainr** [comment]
The official way to support HDFS HA is with HttpFs, why not use it instead?

https://hadoop.apache.org/docs/r2.4.1/hadoop-hdfs-httpfs/

**Comment by miho120** [comment]
@romainr Yes and no at the same time. What in case if HttpFs server is unavailable? It's more like additional HA feature and covers more unexpected situations.

**Comment by romainr** [comment]
Would it be something still needed?

**Pull request closed without merging**
