### PR TITLE
[Trino] Reformatting the return of the show_table for autocomplete call

### PR DESCRIPTION
**Pull request by agl29**
## What changes were proposed in this pull request?

- Reformatting the return of the show_table for autocomplete call as the earlier format did not match our existing code.
- Due to a different format, samples for tables were missing in the left assist.

## How was this patch tested?

- Locally

### CODE REVIEW

**Review by Harshg999 — APPROVED** [review]
LGTM!

**Review by bjornalm — COMMENTED** [review]
LGTM, but shouldn't we add a unit test for this?

**Comment by agl29** [comment]
> LGTM, but shouldn't we add a unit test for this?

Yes, agreed. We will add all the tests for Trino in another PR. For V1, we decided that all functionality should work, and then we can add the rest of the things slowly.

**Review by wing2fly — APPROVED** [review]
Beside unit test, some upstream doc also?

**Pull request merged**
