### PR TITLE
Default Home directory button in Filebrowser should be sanitized and should trust the input from untrusted source

### PR DESCRIPTION
**Pull request by Akhilsnaik**
### What changes were proposed in this pull request?

- #1965  -[filebrowser] GH-1965 Default Home directory button in Filebrowser should be sanitized and should trust the input from untrusted source

## How was this patch tested?

- Tested manually, The Fix works well.
- 
Screenshot 2021-04-01 at 5 58 19 PM

### CODE REVIEW

**Review by romainr — APPROVED** [review]

**Review by romainr — COMMENTED** [review]
PS: proper way is probably to properly escape instead?

**Comment by Akhilsnaik** [comment]
> PS: proper way is probably to properly escape instead?

The URL is created by an mako rendering, we cannot use the UI framework sanitisation code here as it wont work. 
Even if we control sanitising ,it's wrong because we where just blindly setting the path from the UI as home directory, even though thats not the case.

**Comment by romainr** [comment]
Feels weird, but please make sure we can still open path in urls ..

**Comment by Akhilsnaik** [comment]
> Feels weird, but please make sure we can still open path in urls ..

it wont impact the way we load the URL ( i am aware navigator and other places we use that feature). Tested well.
I will commit it once @JohanAhlen  approves the request.

**Review by JohanAhlen — APPROVED** [review]

**Comment by JohanAhlen** [comment]
> > Feels weird, but please make sure we can still open path in urls ..
> 
> it wont impact the way we load the URL ( i am aware navigator and other places we use that feature). Tested well.
> I will commit it once @JohanAhlen approves the request.

Indeed odd but the ko bug seems real, if I remember correctly we had issues with using I18n as well in data-bind in the past for the same reason.

Changes are just to the home and trash links so don't see how it would affect the url paths.

**Pull request merged**
