### PR TITLE
result is inconsistent between Hive results On Web and Response Preview

### PR DESCRIPTION
**Pull request by cgkbfrd**
## What changes were proposed in this pull request?
issue  #3399 
- if the length of a field in result more than 16, then cast it to string

## How was this patch tested?

- (Please explain how this patch was tested. Ex: unit tests, manual tests)
- (If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

### CODE REVIEW

**Comment by cgkbfrd** [comment]
Hello  @anutron @maiha @subtleGradient，I think the codes I posted is right, but I don't know why the compile is failed，please help me to check.

**Comment by Harshg999** [comment]
@cgkbfrd `ci/circleci: build-py-38-arm64` is unrelated to your change.

**Comment by Harshg999** [comment]
@bjornalm @JohanAhlen @nidhibhatg @agl29  - Is this a JS issue? Can this be fixed from the UI side?

**Comment by bjornalm** [comment]
@Harshg999 First just a note that the bug described in https://github.com/cloudera/hue/issues/3399 is from the Editor v2 which still is behind a feature flag. But, there is a real problem when a JSON object from Python API is including integers that could be larger than the maximum safe integer limit of Javascript. Modern JS can handle larger numbers using BigInt but the built in JSON parser doesn't.

So we can either introduce another JSON parser on the client side to handle this properly, or we can solve it by passing larger numbers as strings, like this PR suggets. For simply displaying the data in the result table I think this fix is sufficient but we might also also need to take special care when these numbers are to be used in the charts etc. If this is an external API we should also consider keeping the API consistent and easy to use for other consumers than the Hue UI.

**Comment by bjornalm** [comment]
@JohanAhlen I think we should be consistent when dealing with this problem and I'm not sure what the strategy has been in the past, but lets discuss when your are back.

**Pull request closed without merging**
