### PR TITLE
Another precision loss fix in rdbms plugin

### PR DESCRIPTION
**Pull request by xq262144**
Another precision loss fix in rdbms plugin

### CODE REVIEW

**Comment by romainr** [comment]
Indeed, thanks!

**Comment by FrommyMind** [comment]
@romainr 

In  CDH6.3.2 we still have this problem, I think this is because the **_Number.MAX_SAFE_INTEGER_** in JS is 9007199254740992, so when we have a bigint value in rdbms that bigger than this MAX value ,the result will been truncated.
image

**Comment by romainr** [comment]
Would recommend to use the new Editor and not RDBMS as not supported anymore: https://docs.gethue.com/administrator/configuration/connectors/

**Comment by FrommyMind** [comment]
Ok,  Thanks a lot

**Pull request merged**
