### PR TITLE
[interpreters] Skip adding all available editors by default for every whitelisted app

### PR DESCRIPTION
**Pull request by Harshg999**
## What changes were proposed in this pull request?

- This change ensures that if a user needs an interpreter X, then user needs to add its config under `[[interpreters]]` section. This way Hue won't be showing all unneeded interpreters and confuse users whenever any app is whitelisted.
- If user still wants to add all default available interpreters for every whitelisted app (old scenario), then they can set the flag `enable_all_interpreters` to `True` in the Hue configs.

## How was this patch tested?

- Manually tested different scenarios of Hue config and verified the editors available on the Hue UI.
- Added new unit tests and updated existing ones.

### CODE REVIEW

**Comment by Harshg999** [comment]
Next steps is to add unit tests for this change.

**Comment by amitsrivastava** [comment]
is this change backwards compatible? Or do users need to update configs after an upgrade?

**Comment by Harshg999** [comment]
PR is ready for review. 
The change is big because of all the code formatting and linting.

**Comment by Harshg999** [comment]
> is this change backwards compatible? Or do users need to update configs after an upgrade?

@amitsrivastava Yes the change is backward compatible. I've added a config `ENABLE_ALL_INTERPRETERS` and set it to False by default. If the users want old behaviour back, they can set it to `True`.

**Comment by amitsrivastava** [comment]
> > is this change backwards compatible? Or do users need to update configs after an upgrade?
> 
> @amitsrivastava Yes the change is backward compatible. I've added a config `ENABLE_ALL_INTERPRETERS` and set it to False by default. If the users want old behaviour back, they can set it to `True`.

Does this mean, no interpreters will show up if they simply do an upgrade and make no config update?

**Comment by Harshg999** [comment]
> > > is this change backwards compatible? Or do users need to update configs after an upgrade?
> > 
> > 
> > @amitsrivastava Yes the change is backward compatible. I've added a config `ENABLE_ALL_INTERPRETERS` and set it to False by default. If the users want old behaviour back, they can set it to `True`.
> 
> Does this mean, no interpreters will show up if they simply do an upgrade and make no config update?

No, it will show interpreters based on existing configs under `[[interpreters]]` and if Hive and Impala are blacklisted.

**Review by amitsrivastava — APPROVED** [review]

**Review by JohanAhlen — APPROVED** [review]
LGTM!

**Review by agl29 — APPROVED** [review]
LGTM!

**Pull request merged**
