### PR TITLE
[ci] Run frontend CI for all PRs

### PR DESCRIPTION
**Pull request by Harshg999**
## What changes were proposed in this pull request?

- Remove file extension restriction for frontend CI
- This is run the Ci check for all PR including backend specific PRs. Reason to go with this is to make frontend CI check as required so that its not skipped even for frontend focused PRs.

### CODE REVIEW

**Review by nidhibhatg — APPROVED** [review]
LGTM!

**Comment by bjornalm** [comment]
So unless the check always run it can't be made required? Wouldn't it be possible to make it conditionally in the jobs

```
jobs:
  python_job:
    if: ${{ contains(github.event.head_commit.modified, '*.py, *.mako .......') }}
    ...

  javascript_job:
    if: ${{ contains(github.event.head_commit.modified, '*.js, *.tsx ......') }}
```

**Review by JohanAhlen — APPROVED** [review]
LGTM!

**Comment by Harshg999** [comment]
> So unless the check always run it can't be made required? Wouldn't it be possible to make it conditionally in the jobs. Something like the below (not sure if github.event.head_commit.modified is still available)
> 
> ```
> jobs:
>   python_job:
>     if: ${{ contains(github.event.head_commit.modified, '*.py, *.mako .......') }}
>     ...
> 
>   javascript_job:
>     if: ${{ contains(github.event.head_commit.modified, '*.js, *.tsx ......') }}
> ```

It was running for UI related file extensions before also but the required tag which we set from repo setting was making it required for all PRs.

**Pull request merged**
