### PR TITLE
JB Progress bar wdg provides 2 different information which was causing issues with fetching of logs

### PR DESCRIPTION
**Pull request by quadoss**
Looking with browser tool and source, identified that the wdg comes out like pattern like below which means that

id="wdg_hive2-cec1745-4d3a-8320-40a3cc1e560b" - this will work with lastIndex('@')
id="wdg_bcedc7ef-bae0-058b-d01a-17078fa73da8" - this will work with lastIndex('-')

So I had to include another condition to satisfy both so any WF which has this type of wdg is handled.

### CODE REVIEW

**Comment by quadoss** [comment]
Seeing the exception in refresh source.

ERROR in ./desktop/core/src/desktop/js/apps/notebook/app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module 'babel-preset-typescript-vue' from '/usr/share/hue'

+++++++++++

[./desktop/core/src/desktop/js/apps/editor/app.js] 2.55 KiB {editor~002699c4} [built] [failed] [1 error]
[./desktop/core/src/desktop/js/apps/jobBrowser/app.js] 2.55 KiB {jobBrowser~002699c4} [built] [failed] [1 error]
[./desktop/core/src/desktop/js/apps/notebook/app.js] 2.55 KiB {notebook~002699c4} [built] [failed] [1 error]
[./desktop/core/src/desktop/js/apps/tableBrowser/app.js] 2.55 KiB {tableBrowser~002699c4} [built] [failed] [1 error]
[./desktop/core/src/desktop/js/hue.js] 2.55 KiB {hue~002699c4} [built] [failed] [1 error]

**Comment by romainr** [comment]
:+1: 

And the CI failure is unrelated indeed (it will work tomorrow around 8am PST with the refreshed image, so re-kick it then).

FYI @JohanAhlen @sreenaths

**Comment by plusplusjiajia** [comment]
I use Hue 4.9, and after applying this patch, still can't show the log button of the oozie job.
image

**Comment by Akhilsnaik** [comment]
@plusplusjiajia  , see if you are having any console error or any error in the hue runcpserver logs.

**Pull request merged**
