### PR TITLE
[docs] Update urlstring for PyAthena connector with new params

### PR DESCRIPTION
**Pull request by pid998877**
## What changes were proposed in this pull request?

- updated docs connector Athena for pull https://github.com/cloudera/hue/pull/3327

@Harshg999

### CODE REVIEW

**Review by Harshg999 — APPROVED** [review]
LGTM!

**Comment by Harshg999** [comment]
To rebase once https://github.com/cloudera/hue/pull/3336 is merged.

**Review by agl29 — APPROVED** [review]
Nice!

**Review by JohanAhlen — COMMENTED** [review]
Nice!

**Pull request merged**
