### PR TITLE
[cve] Bump dnspython package to 2.6.1 and eventlet package to 0.35.2 …

### PR DESCRIPTION
**Pull request by rayliu0**
…[#3772]

## What changes were proposed in this pull request?

- (Please fill in changes proposed in this fix)

## How was this patch tested?

- (Please explain how this patch was tested. Ex: unit tests, manual tests)
- (If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

### CODE REVIEW

**Comment by Harshg999** [comment]
Hey @rayliu0, thank you for contributing the fix!
We'll review this PR soon.

**Review by amitsrivastava — APPROVED** [review]
Thank @rayliu0 for the PR.

**Review by amitsrivastava — CHANGES_REQUESTED** [review]
@rayliu0 Upgrade to latest versions of dnspyton and eventlet is breaking things and it will require an upgrade of gunicorn. I have therefore proposed a separate PR https://github.com/cloudera/hue/pull/3796 to bring in only Tudoor/DoS related fixes into Hue in the short term while we work to upgrade gunicorn.

**Comment by Harshg999** [comment]
Closing this PR because the CVE fixes are added in the ext-py3 packages explicitly due to gunicorn issue.

**Pull request closed without merging**
