### PR TITLE
Supports hiveserver2 load balancing Support reconnect after hiveserver2 down

### PR DESCRIPTION
**Pull request by ganborui**
Assign the hiveserver2 address according to the hash value of the username. When the connected hiveserver2 is down, it will automatically find other available hiveserver2 for reconnection

### CODE REVIEW

**Comment by romainr** [comment]
Any chance you could rebase on master, it seems like the branch is pretty old now?

**Comment by ganborui** [comment]
Sorry, I try again

**Comment by romainr** [comment]
Replaced by https://github.com/cloudera/hue/pull/1005

**Comment by ganborui** [comment]
Sorry, I'm not very familiar with the use of github, I'm troublesome for you, I resubmit the code




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Romain Rigaux"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月1日(星期天) 下午5:52
收件人:&nbsp;"cloudera/hue"<hue@noreply.github.com&gt;;
抄送:&nbsp;"甘博瑞"<276685422@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cloudera/hue] Supports hiveserver2 load balancing Support reconnect after hiveserver2 down (#1002)




Any chance you could rebase on master, it seems like the branch is pretty old now?

**Pull request closed without merging**
