### PR TITLE
change exception error to AssertionError and modify regex

### PR DESCRIPTION
**Pull request by maulikjs**

### CODE REVIEW

**Comment by romainr** [comment]
Thanks!

**Comment by iqueryio** [comment]
Actually, it seems that it breaks 

`======================================================================
ERROR: aws.s3.s3_test.test_s3datetime_to_timestamp
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/share/hue/desktop/libs/aws/src/aws/s3/s3_test.py", line 69, in test_s3datetime_to_timestamp
    assert_raises(ValueError, f, '2/26/2015 20:42:07')
  File "/usr/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/usr/share/hue/desktop/libs/aws/src/aws/s3/__init__.py", line 137, in s3datetime_to_timestamp
    assert datetime[-5:] == re.findall('(?i)\.\d{3}Z$', datetime)[0], 'Time [%s] is not in GMT.' % datetime
IndexError: list index out of range`

**Comment by romainr** [comment]
Actually, it seems that it breaks

`======================================================================
ERROR: aws.s3.s3_test.test_s3datetime_to_timestamp
Traceback (most recent call last):
File "/usr/share/hue/build/env/local/lib/python2.7/site-packages/nose-1.3.7-py2.7.egg/nose/case.py", line 197, in runTest
self.test(*self.arg)
File "/usr/share/hue/desktop/libs/aws/src/aws/s3/s3_test.py", line 69, in test_s3datetime_to_timestamp
assert_raises(ValueError, f, '2/26/2015 20:42:07')
File "/usr/lib/python2.7/unittest/case.py", line 473, in assertRaises
callableObj(*args, **kwargs)
File "/usr/share/hue/desktop/libs/aws/src/aws/s3/init.py", line 137, in s3datetime_to_timestamp
assert datetime[-5:] == re.findall('(?i).\d{3}Z$', datetime)[0], 'Time [%s] is not in GMT.' % datetime
IndexError: list index out of range`

**Comment by romainr** [comment]
FYI this was reverted in https://github.com/cloudera/hue/commit/016112c924746d8290c0b6da2813b92072cd26c9
to unblock the CI.

Good news though is now the checks will also show on the PR if they build the build. 

And we can just re-revert the commit when we have a fix for the test

**Pull request merged**
