### PR TITLE
Translate blog posts into Japanese (August and September 2020)

### PR DESCRIPTION
**Pull request by kawamon**
Hi Hue team,

Congratulations on the release of Hue 4.8!

I translated five Hue blog posts into Japanese. (August, and September 2020)
Please let me know if you have any questions.

Best Regards,
Tatsuo

### CODE REVIEW

**Comment by romainr** [comment]
Nice Tatsuo!

Just, could we have commit messages that follow the standard?

```
'[Japanese] translated 'sql-editor-user-experience' blog into Japanese' is not a valid commit message, please see for examples:
  HUE-9374 [impala] Use 26000 as default for thrift-over-http
  [livy] Add numExecutors options (#1238)
```

**Comment by kawamon** [comment]
Hey Romain,

I just want to make sure, do I need a JIRA ticket number or pull request ID for the commit message?

**Comment by romainr** [comment]
PR id is good, cf. the second example!

Thanks!

**Comment by kawamon** [comment]
Hi Romain,

I modified my past commit message as below. Please let me know if you find any issues.

"[blog] localize sql-editor-user-experience blog into Japanese (#1274)"
https://github.com/kawamon/hue/commit/95aa4372bb153e2eeeaccb8ef481f03182818995

Best Regards,
Tatsuo

**Comment by romainr** [comment]
Could you do a clean rebase of the branch and force push? (there are 841 commits in the PR..)

If you click on the 'details' link, you will see it is not correct still:

```
'[Japanese] translated 'sql-editor-user-experience' blog into Japanese' is not a valid commit message, please see for examples:
  HUE-9374 [impala] Use 26000 as default for thrift-over-http
  [livy] Add numExecutors options (#1238)
```

**Comment by kawamon** [comment]
Hi Romain,

Sorry, It seems that a lot of commits have been created when you changed my past commit message.
I re-forked Hue repository and created a new pull request. (#1281)

Tatsuo

**Comment by romainr** [comment]
Replaced by https://github.com/cloudera/hue/pull/1281

**Pull request closed without merging**
