### PR TITLE
[desktop] Fix oozie api when Py3 is used (#1262)

### PR DESCRIPTION
**Pull request by elukey**

### CODE REVIEW

**Comment by elukey** [comment]
This currently fails due to "'Merge branch 'master' into py3_json_encode' is not a valid commit message, please see for examples:" so the rest looks good from the CI's perspective :)

**Comment by romainr** [comment]
I see, excellent and the code looks good!

Would you mind just doing a rebase and force pushing to the PR branch so that it clears the CI naming issue?

**Comment by elukey** [comment]
@romainr should be good now!

**Comment by romainr** [comment]
Indeed, excellent, thank you!

**Pull request merged**
