### PR TITLE
[frontend] Modify tooltip which can be passed in params now

### PR DESCRIPTION
**Pull request by Harshg999**
## What changes were proposed in this pull request?

- To clear a bit of UI, 'Database' is removed and the tooltip is modified as 'Database X' where X is the current database selected.
- Tooltip can be passed in params now which can help in clearing more such text on editor such as "Text" besides "Database" before.
- This gives flexibility whether to use this tooltip or have the previous one is different cases.

## How was this patch tested?

- Tested manually
Screenshot 2021-02-01 at 10 02 57 AM

### CODE REVIEW

**Comment by Harshg999** [comment]
Fixes #1710

**Review by JohanAhlen — APPROVED** [review]
Nice one!

**Comment by JohanAhlen** [comment]
To fix the test, run "npm run test-dev", let it finish the first pass, then you can press "u" to update the snapshots.

**Comment by Harshg999** [comment]
> To fix the test, run "npm run test-dev", let it finish the first pass, then you can press "u" to update the snapshots.

Thank you!

**Comment by romainr** [comment]
Nice!

And:
> To fix the test, run "npm run test-dev", let it finish the first pass, then you can press "u" to update the snapshots.

Maybe adding a "how to update snapshot test" line to?

https://docs.gethue.com/developer/development/#running-the-ui-tests

**Review by romainr — APPROVED** [review]

**Comment by Harshg999** [comment]
> Nice!
> 
> And:
> 
> > To fix the test, run "npm run test-dev", let it finish the first pass, then you can press "u" to update the snapshots.
> 
> Maybe adding a "how to update snapshot test" line to?
> 
> https://docs.gethue.com/developer/development/#running-the-ui-tests

On it!

**Pull request merged**
