### PR TITLE
HUE-9467 [sqoop] [editor] Hue showing Sqoop command as running even when its finished

### PR DESCRIPTION
**Pull request by Akhilsnaik**
What changes were proposed in this pull request?
HUE-9467 [sqoop] [editor] Hue showing Sqoop command as running even when its finished

How was this patch tested?

Manually Tested for sqoop editor in Hue 

Screenshot 2020-09-09 at 8 09 56 PM

### CODE REVIEW

**Comment by romainr** [comment]
Good and could you also update the Python style of the files changed?

cf.

`************* Module filebrowser.conf
apps/filebrowser/src/filebrowser/conf.py:65: [C0301(line-too-long), ] Line too long (173/140)
************* Module useradmin.models
apps/useradmin/src/useradmin/models.py:36: [C0301(line-too-long), ] Line too long (143/140)
************* Module desktop.models
desktop/core/src/desktop/models.py:502: [C0301(line-too-long), ] Line too long (184/140)
desktop/core/src/desktop/models.py:503: [C0301(line-too-long), ] Line too long (142/140)
desktop/core/src/desktop/models.py:633: [C0301(line-too-long), ] Line too long (143/140)
desktop/core/src/desktop/models.py:970: [C0301(line-too-long), ] Line too long (141/140)
desktop/core/src/desktop/models.py:979: [W0311(bad-indentation), ] Bad indentation. Found 4 spaces, expected 2
desktop/core/src/desktop/models.py:1608: [C0326(bad-whitespace), ] No space allowed after bracket
        ( (Q(document2permission__users=user) | Q(document2permission__groups__in=user.groups.all())) &
        ^
desktop/core/src/desktop/models.py:1609: [C0326(bad-whitespace), ] No space allowed before bracket
          ~Q(owner=user) )
                         ^
desktop/core/src/desktop/models.py:1762: [C0301(line-too-long), ] Line too long (143/140)
desktop/core/src/desktop/models.py:2115: [C0301(line-too-long), ] Line too long (152/140)
************* Module notebook.connectors.oozie_batch
desktop/libs/notebook/src/notebook/connectors/oozie_batch.py:70: [C0301(line-too-long), ] Line too long (201/140)
desktop/libs/notebook/src/notebook/connectors/oozie_batch.py:75: [C0301(line-too-long), ] Line too long (178/140)
desktop/libs/notebook/src/notebook/connectors/oozie_batch.py:117: [C0326(bad-whitespace), ] Exactly one space required after :
        'data':  [[line] for line in results.split('\n')],  # hdfs_link()
              ^

-----------------------------------
Your code has been rated at 9.91/10`

**Comment by Akhilsnaik** [comment]
retest this please

**Comment by romainr** [comment]
Could you do a clean rebase and for push to your branch? (or do a new PR)

Commit message example:

`HUE-9467 Fix pythonlint Errors (asnnaik)`
-->
`HUE-9467 [desktop] Fix pythonlint Errors`

**Comment by Akhilsnaik** [comment]
Closing the PR as there is CI build errors, will create an new one.

**Pull request closed without merging**
