### PR TITLE
HUE-9570 [ui] Rewramp deXSS with sanitize-html package

### PR DESCRIPTION
**Pull request by Akhilsnaik**
**What changes were proposed in this pull request?**
HUE-9570 [ui] Rewramp deXSS with sanitize-html package

**How was this patch tested?**
 
- Tested the Function hueUtils.deXSS for many scenarios .
-  The function should sanitize the onerror onclick and another harmfull tags , The function should sanitize script tag 
-  Verified the UI works Fine with Desired Output For Tags Like <str'ong/>, <h1'/>  <p'/>

**The Fix Works Fine.**
Screenshot 2020-11-21 at 4 33 41 PM

### CODE REVIEW

**Comment by romainr** [comment]
This is nice!

Maybe just could we add the tests as a real test suite? (so that it is automated and documented, even if the core logic comes from the sanitize-html MIT lib)

**Comment by Akhilsnaik** [comment]
working on adding test cases

**Comment by Akhilsnaik** [comment]
Added 7 testcases to cover the scenario :
 
`asnaik@asnaik-MBP15-2:~/Documents/Code/forked_cloudera_hue/hue|CDH-85073⚡ ⇒  jest desktop/core/src/desktop/js/utils/hueUtils.test.js
 PASS  desktop/core/src/desktop/js/utils/hueUtils.test.js
  hue.utils.js
    ✓ should change completely the URL (3 ms)
    ✓ should change just a parameter in the URL (1 ms)
    ✓ should remove a parameter in the URL
    ✓ should remove JS code from a string (1 ms)
    ✓ Should not remove strong tag from a string (1 ms)
    ✓ Should remove img tag from a string
    ✓ Should not remove p tag from a string
    ✓ Should not remove h1 tag from a string (1 ms)
    ✓ should preserve entities as such
    ✓ should dump comments (1 ms)
    ✓ should dump an uppercase javascript url

Test Suites: 1 passed, 1 total
Tests:       11 passed, 11 total
Snapshots:   0 total
Time:        2.42 s, estimated 5 s
Ran all test suites matching /desktop\/core\/src\/desktop\/js\/utils\/hueUtils.test.js/i.`

**Review by romainr — APPROVED** [review]
Nice automation :)

**Review by JohanAhlen — APPROVED** [review]
Very clean!

**Pull request merged**
