### PR TITLE
Add numExecutors and fix files option issue

### PR DESCRIPTION
**Pull request by xiaop1987**
* Add numExecutors in POST Batch request;
* Fix problem of https://github.com/cloudera/hue/issues/195

### CODE REVIEW

**Comment by erickt** [comment]
The `--num-executors` part looks good, but as I mentioned in #195, could you factor out the `files://` section since it would allow malicious users to access livy files they shouldn't have access to?

**Comment by xiaop1987** [comment]
Hi @erickt I've revert the files option related code~

**Comment by xiaop1987** [comment]
Hi @erickt , another problem found when livy get status of an application, The code in Client.scala shown that yarnClient init with default YarnConfiguation which's yarn.resourcemanager.address is 0.0.0.0:8032, for can't get application status, the batch status will keep in 'running'. So I reload the yarn-site.conf by env['HADOOP_CONF_DIR']

**Comment by erickt** [comment]
Thanks!

**Pull request merged**
