### PR TITLE
Hue [py3] Fixing b64encode string issue

### PR DESCRIPTION
**Pull request by ranade1**
(cherry picked from commit 61f095c03c46e72f4c3e8feedae3f24f662abb66)

## What changes were proposed in this pull request?

- (Please fill in changes proposed in this fix)

## How was this patch tested?

- (Please explain how this patch was tested. Ex: unit tests, manual tests)
- (If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

### CODE REVIEW

**Comment by ranade1** [comment]
recheck

**Comment by ranade1** [comment]
recheck

**Review by wing2fly — APPROVED** [review]
LGTM

**Comment by Harshg999** [comment]
Please fix the failing unit test.
```
======================================================================
FAIL: test_check_access_s3 (desktop.lib.raz.raz_client_test.RazClientTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/repo/desktop/core/src/desktop/lib/raz/raz_client_test.py", line 362, in test_check_access_s3
    verify=False
  File "/usr/lib/python3.6/unittest/mock.py", line 814, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: post('https://raz.gethue.com:8080/api/authz/s3/access?delegation=mock_RAZ_token', headers={'Content-Type': 'application/json', 'Accept-Encoding': 'gzip,deflate'}, json={'requestId': 'mock_request_id', 'serviceType': 's3', 'serviceName': 'cm_s3', 'user': 'gethue', 'userGroups': [], 'clientIpAddress': '', 'clientType': '', 'clusterName': 'myCluster', 'clusterType': '', 'sessionId': '', 'accessTime': '', 'context': {'S3_SIGN_REQUEST': b'CiRodHRwczovL2dldGh1ZS10ZXN0LnMzLmFtYXpvbmF3cy5jb20QATIYZ2V0aHVlL2RhdGEvY3VzdG9tZXIuY3N2OABCAnMzSgJzMw=='}}, verify=False)
Actual call: post('https://raz.gethue.com:8080/api/authz/s3/access?delegation=mock_RAZ_token', headers={'Content-Type': 'application/json', 'Accept-Encoding': 'gzip,deflate'}, json={'requestId': 'mock_request_id', 'serviceType': 's3', 'serviceName': 'cm_s3', 'user': 'gethue', 'userGroups': [], 'clientIpAddress': '', 'clientType': '', 'clusterName': 'myCluster', 'clusterType': '', 'sessionId': '', 'accessTime': '', 'context': {'S3_SIGN_REQUEST': 'CiRodHRwczovL2dldGh1ZS10ZXN0LnMzLmFtYXpvbmF3cy5jb20QATIYZ2V0aHVlL2RhdGEvY3VzdG9tZXIuY3N2OABCAnMzSgJzMw=='}}, verify=False)
```

**Comment by ranade1** [comment]
> Please fix the failing unit test.
> 
> ```
> ======================================================================
> FAIL: test_check_access_s3 (desktop.lib.raz.raz_client_test.RazClientTest)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/root/repo/desktop/core/src/desktop/lib/raz/raz_client_test.py", line 362, in test_check_access_s3
>     verify=False
>   File "/usr/lib/python3.6/unittest/mock.py", line 814, in assert_called_with
>     raise AssertionError(_error_message()) from cause
> AssertionError: Expected call: post('https://raz.gethue.com:8080/api/authz/s3/access?delegation=mock_RAZ_token', headers={'Content-Type': 'application/json', 'Accept-Encoding': 'gzip,deflate'}, json={'requestId': 'mock_request_id', 'serviceType': 's3', 'serviceName': 'cm_s3', 'user': 'gethue', 'userGroups': [], 'clientIpAddress': '', 'clientType': '', 'clusterName': 'myCluster', 'clusterType': '', 'sessionId': '', 'accessTime': '', 'context': {'S3_SIGN_REQUEST': b'CiRodHRwczovL2dldGh1ZS10ZXN0LnMzLmFtYXpvbmF3cy5jb20QATIYZ2V0aHVlL2RhdGEvY3VzdG9tZXIuY3N2OABCAnMzSgJzMw=='}}, verify=False)
> Actual call: post('https://raz.gethue.com:8080/api/authz/s3/access?delegation=mock_RAZ_token', headers={'Content-Type': 'application/json', 'Accept-Encoding': 'gzip,deflate'}, json={'requestId': 'mock_request_id', 'serviceType': 's3', 'serviceName': 'cm_s3', 'user': 'gethue', 'userGroups': [], 'clientIpAddress': '', 'clientType': '', 'clusterName': 'myCluster', 'clusterType': '', 'sessionId': '', 'accessTime': '', 'context': {'S3_SIGN_REQUEST': 'CiRodHRwczovL2dldGh1ZS10ZXN0LnMzLmFtYXpvbmF3cy5jb20QATIYZ2V0aHVlL2RhdGEvY3VzdG9tZXIuY3N2OABCAnMzSgJzMw=='}}, verify=False)
> ```
fixed

**Pull request merged**
