### PR TITLE
[future] upgrading the future lib

### PR DESCRIPTION
**Pull request by agl29**
## What changes were proposed in this pull request?

- future 0.18.2 -> 0.18.3

## How was this patch tested?

- checked all the commits in the 0.18.3 version
- locally
- E2E testing

### CODE REVIEW

**Review by bjornalm — APPROVED** [review]
LGTM. Is the upgrade needed for functionality or is it CVE related?

**Comment by Harshg999** [comment]
To check E2E in Py3 live cluster for regressions and update the PR.

**Comment by agl29** [comment]
> LGTM. Is the upgrade needed for functionality or is it CVE related?

CVE related.

**Comment by agl29** [comment]
> To check E2E in Py3 live cluster for regressions and update the PR.

Yes, tested E2E. All the basic functions are working fine.

**Review by Harshg999 — APPROVED** [review]
LGTM!

**Review by wing2fly — APPROVED** [review]

**Pull request merged**
