### PR TITLE
[Python3.9] Add github actions for py3.9

### PR DESCRIPTION
**Pull request by agl29**
## What changes were proposed in this pull request?

- Github actions added for python3.9

## How was this patch tested?

- Manually
- In this PR itself we can see Python 3.9 CI (checks)

### CODE REVIEW

**Review by bjornalm — APPROVED** [review]
LGTM

**Review by JohanAhlen — APPROVED** [review]
LGTM!

**Comment by Harshg999** [comment]
Maybe let's try reusing the existing py3 CI and adding 3.9 in the matrix? I think that way we wont need a new explicit CI check and it can be expanded for more py version in the future.

**Comment by agl29** [comment]
> Maybe let's try reusing the existing py3 CI and adding 3.9 in the matrix? I think that way we wont need a new explicit CI check and it can be expanded for more py version in the future.

Yup, good idea.

**Review by Harshg999 — APPROVED** [review]
Looks good now!

**Pull request merged**
