### PR TITLE
[Filebrowser] Add get delegation token logic for secure hadoop (#3301) (Related with: #3324 )

### PR DESCRIPTION
**Pull request by SoniaComp**
What changes were proposed in this pull request?
I am working on integrating Hue with SecureHadoop as a ProxyUser.
I found that the behavior of ProxyUser in WebHDFS FileBrowser needs to be enhanced.
When "security_enabled" is true, [only "read_url" method use delegation token](https://github.com/cloudera/hue/blob/master/desktop/libs/hadoop/src/hadoop/fs/webhdfs.py#L565).

I want to modify the code
so that a user who has been impersonated from Hue(a proxy user) can issue a Delegation Token when using WebHDFS.
(https://github.com/cloudera/hue/discussions/3323)

### CODE REVIEW

**Comment by bjornalm** [comment]
Hi @SoniaComp and thanks for contributing again :-)
@ranade1 @amitsrivastava can you have a look?

**Comment by SoniaComp** [comment]
I use this bug fix in my secure hadoop environment successfully, so I'm sure that this bug fix work well.
I want to get feedbacks from other engineers. Thank you for checking the codes 🙇‍♀️

**Comment by bjornalm** [comment]
@ranade1 friendly reminder from our contributor here, can you take a look at this PR?

**Comment by SoniaComp** [comment]
@ranade1 Thank you for your comment! I will change that library with better one.

**Comment by SoniaComp** [comment]
@bjornalm @ranade1  
I changed cachetools to django core cache which is thread-safe.

**Comment by SoniaComp** [comment]
I tested this code and confirmed that it works properly after fixing the bug.

**Comment by bjornalm** [comment]
@SoniaComp Thanks! @ranade1 Can you have another look?

**Comment by SoniaComp** [comment]
Thank you for your reviews! Are there any parts in this PR that could be improved further?

**Comment by ranade1** [comment]
Hello @SoniaComp , Thank you for putting code changes. I have specific questions.

1. Have you tried this code where Hue HA is enabled? (For example multiple Hue servers are running behind single Hue LB).
2. Have you tried using multiple users using Hue HA(above configuration)?

**Comment by SoniaComp** [comment]
Hi! I appreciate for the good questions! 😊
1. I am running hue on a Kubernetes cluster using the Hue helm chart. I used an image built using the code written in PR.
2. And multiple users authenticated through in-house LDAP are using Hue's hdfs filebrowser function with separate permissions using this Hue. (hue was set to hdfs proxy user)

**Comment by SoniaComp** [comment]
Do I need more test for this code?

**Comment by SoniaComp** [comment]
@ranade1 @bjornalm  Hi! I am currently running hue with this code for over 100 users. If there are any areas that need further development, I will make corrections.

**Comment by bjornalm** [comment]
@SoniaComp thank you. @ranade1 @amitsrivastava Can we please take a moment to see if we can get this PR merged or if additional changes/tests are required?

**Comment by eubnara** [comment]
This is needed.

**Comment by eubnara** [comment]
@SoniaComp 
It is about to be closed. :sweat_smile:

**Comment by eubnara** [comment]
cc. @SoniaComp

**Comment by eubnara** [comment]
cc. @bjornalm @ranade1 @amitsrivastava

**Pull request closed without merging**
