### PR TITLE
[slack] Delete 'has_hue_permission' attr set by rewrite_user 

### PR DESCRIPTION
**Pull request by Harshg999**
## What changes were proposed in this pull request?

- Deleted 'has_hue_permission' from user object set by rewrite_user when its job is done.
- Ref. https://github.com/cloudera/hue/issues/1917

### CODE REVIEW

**Comment by romainr** [comment]
What is the goal of this PR?

**Comment by Harshg999** [comment]
> What is the goal of this PR?

To propose a potential fix and iterate further for the unsecure use of rewrite_user as mentioned in https://github.com/cloudera/hue/pull/1862#discussion_r594668310 and https://github.com/cloudera/hue/issues/1917

Were you refering to doc access check here @romainr or how is it unsecure??

**Comment by romainr** [comment]
It looks like a hack and not sure why is unsecure, check perms is related to Hue permissions. Maybe add a test or detail more the fix and it will be easier to understand?

**Comment by Harshg999** [comment]
`has_hue_permission` is an UserProfile attribute and when tried testing, not able to find the reason why it can be unsecure by setting it with rewrite_user, its basically return a boolean value of whether a particular user has access to an app or not with given action I think.
Therefore, closing this PR for now!

**Pull request closed without merging**
