### PR TITLE
sovle the problem about creating a partition

### PR DESCRIPTION
**Pull request by fatherfox**
To generating a partition when created a new table manually,there's a problem in rendering partition form because of missing the codes which were committed  below.

### CODE REVIEW

**Comment by romainr** [comment]
Don't we need some changes in render_column() in create_table_manually.mako too?

**Comment by fatherfox** [comment]
just only modifying the PartitionTypeForm in apps/beeswax/src/beeswax/forms.py could fix the problem.
wish could help you ~~~~

**Comment by romainr** [comment]
I will look again but I don't see any changes on the page

**Comment by fatherfox** [comment]
when click the button "Add a partition" before the change ,the page can not be rendered,the exception likes u"Key 'char_length' not found in Form".Cause of the exception is that the class "PartitionTypeForm" in apps/beeswax/src/beeswax/forms.py miss some fields.
After adding the fileds,it will work well.

**Comment by romainr** [comment]
Oh I get it!

Thanks! https://github.com/cloudera/hue/commit/0ea363ba10584f29be95d9c1727b06eab165abf7

**Pull request closed without merging**
