### PR TITLE
[importer] added header reformatting for local file upload

### PR DESCRIPTION
**Pull request by michael-brine**
-Automatically replaces local file upload table headers white spaces with underscores and changes all letters to lowercase
-uses a list comprehension to .replace(" ", "_").lower(), the first row of an uploaded file, this is stored separately  from the raw file so if header is unchecked it reverts to the original first line of doc and uses either default, field_1 headers, or user inputed headers. 
-tested both checked and unchecked local file to table uploads, on hive

### CODE REVIEW

**Review by romainr — COMMENTED** [review]
Nice! The logic looks good!

@agl29 do you want it show how to add a unit test? 

Michael you also have some examples in the dev docs (and in the existing test files)

**Comment by agl29** [comment]
@michael-brine  you can add a [unit test in](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/unit-tests/) a file like 'filename_test.py'. For eg we are adding some unit tests for [sql.py](https://github.com/cloudera/hue/blob/master/desktop/libs/indexer/src/indexer/indexers/sql.py) in [sql_tests.py](https://github.com/cloudera/hue/blob/master/desktop/libs/indexer/src/indexer/indexers/sql_tests.py). 
You can follow the [doc](https://docs.gethue.com/developer/development/#running-the-api-tests) on how we are doing this.  
For any query, you can ping me on slack as well. @ayush.goyal

**Comment by agl29** [comment]
@michael-brine  In this PR you can add one more thing -> replace '.' (dot) with '_'

**Comment by romainr** [comment]
:+1: when we can add a test!

**Pull request closed without merging**
