### PR TITLE
[doc] sort by document depth before import documents

### PR DESCRIPTION
**Pull request by sumtumn**
## What changes were proposed in this pull request?

- (Please fill in changes proposed in this fix)
As described in https://github.com/cloudera/hue/issues/648 , let's simplify the process to reproduce this:
1. Add directory a;
2. Add notebook b in directory a;
3. Add directory c;
4. Move notebook b from directory a to directory c;
5. Export a b c;
6. Delete a b c(Move to transh and empty trash);
7. Import

This happens because the exported documents are sorted by primary key, this is ok when we don't move files and directories. But if we move files and direcotries, it may happens that a smaller primary key notebook may be in a bigger primary key directory, this makes loaddata process failed. So before importing documents, we just sort the documents by depth.
## How was this patch tested?

- (Please explain how this patch was tested. Ex: unit tests, manual tests)
manual tests

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

### CODE REVIEW

**Review by Harshg999 — COMMENTED** [review]
Interesting case, thanks for sending a PR!

Suggestion: Should we add the logic in a helper method, something like `_sort_docs_by_depth()`?


@quadoss @wing2fly @ranade1 @amitsrivastava - Can someone please take a look? Any side effects it can have on any existing functionality?

**Comment by Harshg999** [comment]
cc: @agl29

**Comment by agl29** [comment]
Hi @sumtumn,
Looks like you are using very old branch, we have already fixed it. Can you please check this in latest Hue?

**Comment by sumtumn** [comment]
> 

@agl29  I found it in 4.10.0, and I reproduced it in 4.11.0 just now.

**Comment by agl29** [comment]
Hello @sumtumn,

The fix for this issue can be found in this [commit](https://github.com/cloudera/hue/pull/3157/commits).
To resolve this issue, you have two options:

Use the latest master branch.
Alternatively, you can cherry-pick the above commit if you specifically want to use it for version 4.11.

**Comment by sumtumn** [comment]
> Hello @sumtumn,
> 
> The fix for this issue can be found in this [commit](https://github.com/cloudera/hue/pull/3157/commits). To resolve this issue, you have two options:
> 
> Use the latest master branch. Alternatively, you can cherry-pick the above commit if you specifically want to use it for version 4.11.

@agl29  Awesome, I will have a try.

**Comment by Harshg999** [comment]
@sumtumn Closing this PR, feel free to reopen the issue/PR if you face this again. Thanks!

**Pull request closed without merging**
