### PR TITLE
[core] Merge HUE-3102 to pysaml2 v4.9.0

### PR DESCRIPTION
**Pull request by wing2fly**
## What changes were proposed in this pull request?

- re-apply HUE-3102 to pysaml2 v4.9.0

## How was this patch tested?

End-to-end with SAML2 IDP

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

### CODE REVIEW

**Review by ranade1 — COMMENTED** [review]
Looks good. Have you tested this change? did you set privkey pem file?

**Comment by wing2fly** [comment]
@ranade1 
I generated a self-signed certificate and use following config in safety valve.

========================================================

[desktop]
redirect_whitelist="^\/.*$,^https:\/\/dev-12345678.oktapreview.com\/.*$"
[[auth]]
`backend=libsaml.backend.SAML2Backend`
[libsaml]
xmlsec_binary=/usr/bin/xmlsec1
metadata_file=/opt/cloudera/security/okta_idp_metadata.xml
key_file=/opt/cloudera/security/key.pem
cert_file=/opt/cloudera/security/cert.pem
key_file_password_script="/opt/cloudera/security/keypass.sh key_pass"
username_source=nameid
name_id_format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
entity_id=yc-c7i5s
base_url=https://yc-c7i5s-1.xxxxx.xxxx:8889
authn_requests_signed=true

========================================================

**Review by romainr — APPROVED** [review]
PS: 
could not submit PR also to pysaml and work with them to get it in? 
and unit test?

**Comment by wing2fly** [comment]
Discussed with Romain. Erick mentioned a PR to pysaml2 in [HUE-3102 commit](https://github.com/cloudera/hue/commit/961d43a5359a8d352e2d2324e282f1f7b1a6f397), but it was rejected because of named pipe won't work on Windows. We will fork pysaml2 and apply patch in gethue.

**Review by ranade1 — APPROVED** [review]

**Pull request merged**
