### PR TITLE
Add first draft of dask-sql parser

### PR DESCRIPTION
**Pull request by nils-braun**
This PR is still heavy under development - I am posting it here just for reference so far :-)

I will add a SQL parser for dask-sql.
See #1480

### CODE REVIEW

**Comment by JohanAhlen** [comment]
Very nice! It all looks good to me. If it helps we can pull this in and do further improvements in separate PRs?

There seems to be some python linting issues, a bit weird as the files the CI build complains about are not part of this PR, perhaps @romainr knows why?

**Review by JohanAhlen — APPROVED** [review]

**Comment by romainr** [comment]
Weird about the CI, especially that master is not the same. I will fix them somehow.

+1 for getting this PR as v1 and iterating as needed, @nils-braun let us know what you prefer!

**Comment by nils-braun** [comment]
Thanks for the quick feedback and very sorry from my side for all the delays... I am also happy to have a first version in hue quickly and iterate on that! I have updated the PR with some style checks and merged master. Let's see what the CI will say.

Just as a reference: on the next PR I am going to add tests and planning to improve the parsed SQL.

**Comment by nils-braun** [comment]
Ok, now it is failing in the do building with a 400 by the twitter API? Not sure if I understand what is going on :-)

**Comment by romainr** [comment]
Looks like it external hosts are getting blocked, e.g. https://github.com/cloudera/hue/pull/1527

Might just convert it to only check for local links that way we are not blocked anymore!

**Comment by romainr** [comment]
Alright, almost ;)

```
/usr/share/hue/desktop/core/src/desktop/js/parse/sql/dasksql/sqlParseSupport.js
  1012:42  error  Insert `·`  prettier/prettier

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

```

**Comment by nils-braun** [comment]
Thanks for baby-sitting my PR :-) 
Next time I should at least check the formatting locally!

**Comment by romainr** [comment]
Came via https://github.com/cloudera/hue/pull/1529!

**Comment by romainr** [comment]
Learning the lints via CI is good enough as it usually happens in the first run ;)

**Pull request closed without merging**
