### PR TITLE
Fix markdown rendering (Issue #1116)

### PR DESCRIPTION
**Pull request by louisdecharson**
The snippet 'Markdown' was not rendering in notebook because of missing parenthesis. Just added the parenthesis and it's working.
See Issue #1116

### CODE REVIEW

**Comment by louisdecharson** [comment]
You’re welcome ! Thank you for the nice product ! 
Just a quick question: if I comment all the interpreters config in hue.ini, all the snippets are available in the notebook. I would expect to have none. Is it a feature or a bug ?

**Comment by romainr** [comment]
Did you leave the section empty like this? (the actual value used can be seen on the page Hue page /hue/desktop/dump_config)

```
[notebook]
[[interpreters]]
```

**Comment by louisdecharson** [comment]
No I've commented the section with `#` as it's by default.

**Comment by romainr** [comment]
Currently it would need to be changed like in above comment.

This will be fixed with https://issues.cloudera.org/browse/HUE-8758

**Pull request merged**
