### PR TITLE
[oozie] Fix usage of iterkeys() and zip() in list_oozie_info template (1270)

### PR DESCRIPTION
**Pull request by elukey**
The function iterkeys() is not available in Python 3, but there seems
to be no real need for an iterator anyway. The zip() call returns an
interator in Python 3, not a list, so the compromise of wrapping
list(zip()) should suffice for this use case.

### CODE REVIEW

**Comment by romainr** [comment]
Nit: # missing in PR number in commit message

**Comment by elukey** [comment]
@romainr fixed thanks!

**Comment by elukey** [comment]
Also added fixes for linter errors..

**Comment by romainr** [comment]
Ok!

Just 3 more it seems!

**Comment by elukey** [comment]
@romainr should be ready to review :)

**Comment by romainr** [comment]
Awesome! Maybe just rebase on master? (or drop the api3.py change)

**Comment by elukey** [comment]
Ah right the usual issue, will rebase :)

**Comment by elukey** [comment]
@romainr done!

**Comment by romainr** [comment]
Will rebase again after https://review.cloudera.org/r/15458/

**Pull request merged**
