### PR TITLE
Revert only py2 version of phoenixdb 1.2.1

### PR DESCRIPTION
**Pull request by agl29**
This reverts commit 49a372848801c6a0e568b6371e1ba66ae9f3bbce.

## What changes were proposed in this pull request?

- Reverting the py2 changes as phoenixdb 1.2.1 has some problem in python build.

### CODE REVIEW

**Comment by agl29** [comment]
@wing2fly please take look.

**Review by Harshg999 — APPROVED** [review]
LGTM!

**Comment by wing2fly** [comment]
@agl29 
update the commit message to "Revert only py2 version of phoenixdb 1.2.1"

**Comment by agl29** [comment]
> @agl29 update the commit message to "Revert only py2 version of phoenixdb 1.2.1"

done

**Review by wing2fly — APPROVED** [review]
Thanks for the update

**Pull request merged**
