### PR TITLE
[cve] Bump cryptography package to 42.0.8

### PR DESCRIPTION
**Pull request by Harshg999**
## What changes were proposed in this pull request?

- Bumping to latest version to remove multiple CVEs:
  - https://github.com/cloudera/hue/security/dependabot/215
  - https://github.com/cloudera/hue/security/dependabot/210
  - https://github.com/cloudera/hue/security/dependabot/189
  - https://github.com/cloudera/hue/security/dependabot/212
  - https://github.com/cloudera/hue/security/dependabot/206
  - https://github.com/cloudera/hue/security/dependabot/191
  - https://github.com/cloudera/hue/security/dependabot/187

### CODE REVIEW

**Comment by amitsrivastava** [comment]
@Harshg999 what kind of testing was done or planned for this?

**Comment by Harshg999** [comment]
Need to test building Hue and its normal working out on different form factors.

**Comment by Harshg999** [comment]
Did general Hue testing on both normal secure Hue cluster and FIPS cluster.

**Review by agl29 — APPROVED** [review]
LGTM

**Review by tabraiz12 — APPROVED** [review]

**Comment by agl29** [comment]
@Harshg999 
have you checked it in ppc builds also?

**Pull request merged**
