### PR TITLE
HUE-2684 [metastore] Support for new datatypes when creating tables manually

### PR DESCRIPTION
**Pull request by iAmGhost**
Added varchar, char, date type support for creating tables
fixed column-spec forms are not showing after adding/deleting columns.

### CODE REVIEW

**Comment by romainr** [comment]
Awesome, going to have a look!

**Comment by romainr** [comment]
It seems to break 4 tests, did you have a chance to test those?
http://gethue.com/tutorial-how-to-run-the-hue-integration-tests/

======================================================================
ERROR: Test field dependency in the create table form
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/nose-0.11.3-py2.6.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/var/lib/jenkins/workspace/hue-testing/apps/beeswax/src/beeswax/tests.py", line 1202, in test_create_table_dependencies
    assert_true(resp.context["columns_form"].forms[0].errors["map_key_type"])
KeyError: 'map_key_type'


ERROR: beeswax.tests.TestBeeswaxWithHadoop.test_partitioned_create_table
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/nose-0.11.3-py2.6.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/var/lib/jenkins/workspace/hue-testing/apps/beeswax/src/beeswax/tests.py", line 1151, in test_partitioned_create_table
    }, follow=True)
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/test/client.py", line 483, in post
    response = super(Client, self).post(path, data=data, content_type=content_type, **extra)
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/test/client.py", line 302, in post
    return self.request(**r)
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/test/client.py", line 444, in request
    six.reraise(*exc_info)
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/var/lib/jenkins/workspace/hue-testing/apps/beeswax/src/beeswax/create_table.py", line 91, in create_table
    'database': database,
  File "/var/lib/jenkins/workspace/hue-testing/desktop/core/src/desktop/lib/django_util.py", line 225, in render
    **kwargs)
  File "/var/lib/jenkins/workspace/hue-testing/desktop/core/src/desktop/lib/django_util.py", line 146, in _render_to_response
    return django_mako.render_to_response(template, *args, **kwargs)
  File "/var/lib/jenkins/workspace/hue-testing/desktop/core/src/desktop/lib/django_mako.py", line 125, in render_to_response
    return HttpResponse(render_to_string(template_name, data_dictionary), **kwargs)
  File "/var/lib/jenkins/workspace/hue-testing/desktop/core/src/desktop/lib/django_mako.py", line 114, in render_to_string_normal
    result = template.render(**data_dict)
  File "/var/lib/jenkins/workspace/hue-testing/desktop/core/src/desktop/lib/test_runners.py", line 54, in _instrumented_test_render
    response = runtime._render(self, self.original_callable_[-1], args, data)
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/Mako-0.8.1-py2.6.egg/mako/runtime.py", line 786, in _render
    **_kwargs_for_callable(callable_, data))
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/Mako-0.8.1-py2.6.egg/mako/runtime.py", line 818, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/Mako-0.8.1-py2.6.egg/mako/runtime.py", line 844, in _exec_template
    callable_(context, *args, **kwargs)
  File "/var/lib/jenkins/workspace/hue-testing/desktop/core/src/desktop/lib/test_runners.py", line 45, in mako_callable_
    return self.original_callable_[-1](context, *args, **kwargs)
  File "/tmp/tmpYvDPfM/beeswax/create_table_manually.mako.py", line 422, in render_body
    __M_writer(escape(unicode(render_column(form, True))))
  File "/tmp/tmpYvDPfM/beeswax/create_table_manually.mako.py", line 58, in render_column
    return render_render_column(context.locals_(__M_locals),form,is_partition_form)
  File "/tmp/tmpYvDPfM/beeswax/create_table_manually.mako.py", line 557, in render_render_column
    __M_writer(escape(unicode(comps.field(form["char_length"], render_default=True))))
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/Django-1.6.10-py2.6.egg/django/forms/forms.py", line 114, in __getitem__
    raise KeyError('Key %r not found in Form' % name)
KeyError: u"Key 'char_length' not found in Form"


FAIL: Checks HQL generation for create table.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/nose-0.11.3-py2.6.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/var/lib/jenkins/workspace/hue-testing/apps/beeswax/src/beeswax/tests.py", line 1104, in test_create_table_generation
    assert_true("my_col" in response.content)
AssertionError: 


======================================================================
FAIL: Test create table wizard
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/hue-testing/build/env/lib/python2.6/site-packages/nose-0.11.3-py2.6.egg/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File "/var/lib/jenkins/workspace/hue-testing/apps/beeswax/src/beeswax/tests.py", line 1333, in test_create_table_import
    assert_equal(resp.context['action'], 'watch-redirect')
AssertionError: '/beeswax/create/import_wizard/default' != 'watch-redirect'

**Comment by iAmGhost** [comment]
I wonder why my new commit is not appearing here, I've fixed it on this commit:
https://github.com/cloudera/hue/commit/b499f62d50affc02efe0f41053298df0f5cdd9d3

**Comment by romainr** [comment]
Yes, not sure why it is not showing up, it is now!

I had already aggregated it to the first commit: https://github.com/cloudera/hue/commit/c7d64b6ef0525ebb5416f2174f6af7698a7cdcc6

Thanks a lot, very nice!

**Pull request closed without merging**
