### PR TITLE
[frontend] Replace ENABLE_NOTEBOOK_2 with ENABLE_HUE_5

### PR DESCRIPTION
**Pull request by JohanAhlen**
The scope of Hue 5 has grown beyond editor/notebook v2 and instead of introducing additional feature flags I've renamed the old one and moved it up in the desktop section of the config.

The ENABLE_HUE_5 flag can be used for any features that we intend to deliver in Hue 5 only.

Manually tested with flag on and off.

### CODE REVIEW

**Review by bjornalm — APPROVED** [review]
Nice work, 

just two questions:

1. I think the nightly build running on demo.gethue.com uses the old `ENABLE_NOTEBOOK_2` flag.  Is that taken into consideration for this PR?
2. Also, just double checking that we don't want this flag  pseudo-distributed.ini.tmpl?

**Comment by JohanAhlen** [comment]
> Nice work,
> 
> just two questions:
> 
> 1. I think the nightly build running on demo.gethue.com uses the old `ENABLE_NOTEBOOK_2` flag.  Is that taken into consideration for this PR?

Yeah, once this is in we'll need to update the demo.gethue config to set this flag instead of the notebook 2 one.

> 2. Also, just double checking that we don't want this flag  pseudo-distributed.ini.tmpl?

When it's not officially supported or dev only we don't update the ini templates.

**Review by Harshg999 — APPROVED** [review]
LGTM! Good to have this under `[desktop]` instead of `[notebook]` now.

**Review by agl29 — APPROVED** [review]
LGTM!!

**Pull request merged**
