### PR TITLE
[helm] Improvements in network Ingress

### PR DESCRIPTION
**Pull request by gmsantos**
## What changes were proposed in this pull request?

This PR contains some improvements to the Nginx network ingress. I can submit each change in different pull requests, just let me know.

- Allow defining extra hosts for ingress
- Support extra annotations for ingress
- Use new ingress apiVersion (`networking.k8s.io/v1`) in Kubernetes 1.19+

## How was this patch tested?

- Manual testing by upgrading an existing deployment

### CODE REVIEW

**Comment by romainr** [comment]
Thanks!

And +1 for 1 PR per improvement! (easier to understand / track)

**Comment by gmsantos** [comment]
@romainr should I bump the chart version after each PR?

**Comment by romainr** [comment]
> @romainr should I bump the chart version after each PR?

No need, we can release when it is all committed

**Comment by gmsantos** [comment]
Closing this in favor of the split PRs ^

**Pull request closed without merging**
