### PR TITLE
[filebrowser] removing extra whitespace between the path

### PR DESCRIPTION
**Pull request by agl29**
## What changes were proposed in this pull request?

- After searching got this link -> https://css-tricks.com/fighting-the-space-between-inline-block-elements/

before commit -> 
Screenshot 2021-08-16 at 11 30 16 PM

### CODE REVIEW

**Comment by agl29** [comment]
Screenshot 2021-08-16 at 11 22 30 PM

**Comment by agl29** [comment]
@JohanAhlen are there any other ways to do it?
1. 
2. ><li>

and if not which one (above) is good?

**Comment by romainr** [comment]
Nice!

Not the expert here. And even if people seem to like negative margin, it probably breaks the copy.

:+1: for me to ident like you did and move on

**Comment by agl29** [comment]
approval?

**Review by romainr — APPROVED** [review]

**Pull request merged**
