### PR TITLE
[core] Add psycopg2-binary 2.9.6 for Python 3

### PR DESCRIPTION
**Pull request by wing2fly**
## What changes were proposed in this pull request?

Add psycopg2-binary 2.9.6 for Python 3

## How was this patch tested?

Please review [Hue Contributing Guide](https://github.com/cloudera/hue/blob/master/CONTRIBUTING.md) before opening a pull request.

### CODE REVIEW

**Review by agl29 — APPROVED** [review]
LGTM!

**Comment by Harshg999** [comment]
License issues?

**Comment by agl29** [comment]
> @wing2fly What about the license issue?

As per the previous discussion we can not include the source code of this lib in our code like we can not put it in ext-py3 folder but we can use it in base_requirements.txt files.

**Comment by agl29** [comment]
@ranade1 @amitsrivastava can you please review this PR?

**Review by ranade1 — APPROVED** [review]
LGTM

**Pull request merged**
