### PR TITLE
[core][cve] Remove werkzeug package

### PR DESCRIPTION
**Pull request by Harshg999**
## What changes were proposed in this pull request?

- This package is having CVEs and I tried to where it is used in the Hue codebase but didnt get any dependency references so looks like its better to remove it.

## How was this patch tested?

- Tested locally

### CODE REVIEW

**Comment by Harshg999** [comment]
@amitsrivastava I feel at some point of time we were using `runserver_plus` and this package was related to it and present from that time in requirements.txt.

**Comment by amitsrivastava** [comment]
> @amitsrivastava I feel at some point of time we were using `runserver_plus` and this package was related to it and present from that time in requirements.txt.

https://github.com/cloudera/hue/commit/5caeba886a57a1bf81b881cfb459e5530017de04 this is probably where Romain added it.

**Review by amitsrivastava — APPROVED** [review]

**Comment by Harshg999** [comment]
Will try testing Ipython shell once to confirm that there is no regression after removing the package.

**Comment by Harshg999** [comment]
Ipython shell looks fine after removing the package.

**Review by agl29 — APPROVED** [review]
LGTM!

**Pull request merged**
