### PR TITLE
[docs] Update Mac Installation section

### PR DESCRIPTION
**Pull request by Harshg999**

### CODE REVIEW

**Comment by Harshg999** [comment]
In my dev build, homebrew python got auto-updated to 3.9.4

However, direct download of python3.7.9 from python.org worked well to resolve python related errors.

So, will it be better to add a preference sentence/point for Intel Macs too? @romainr

**Comment by Harshg999** [comment]
Also on the Github labels side, Adding a `docs` label triggers the autocomplete action to be checked @romainr. Is it expected?

**Review by romainr — APPROVED** [review]

**Comment by romainr** [comment]
> In my dev build, homebrew python got auto-updated to 3.9.4
> 
> However, direct download of python3.7.9 from python.org worked well to resolve python related errors.
> 
> So, will it be better to add a preference sentence/point for Intel Macs too? @romainr

Nice, any non obvious hint is too to document!

**Comment by romainr** [comment]
> Also on the Github labels side, Adding a `docs` label on this PR triggers the autocomplete action to be checked @romainr. Is it expected?

Should be a no-op, I just looked and could not see what's difference? Do you mean the 'autosquash' action?

**Comment by Harshg999** [comment]
> > Also on the Github labels side, Adding a `docs` label on this PR triggers the autocomplete action to be checked @romainr. Is it expected?
> 
> Should be a no-op, I just looked and could not see what's difference? Do you mean the 'autosquash' action?

My bad, yes I meant the `Autosquash` action.

**Comment by romainr** [comment]
Good catch! 

Maybe because of the 'labels' https://github.com/cloudera/hue/blob/master/.github/workflows/autosquash.yml#L12 (and not having put a specific label, will have to dig more)

**Pull request merged**
