### PR TITLE
[presto] fix result duplicate

### PR DESCRIPTION
**Pull request by penggongkui**
#1576

### CODE REVIEW

**Comment by romainr** [comment]
Shouldn't we fix it in the SqlAlchemy connector instead?

**Comment by penggongkui** [comment]
It should fixed in the pyhive？

**Comment by romainr** [comment]
I would need to look a bit more, but it feels fishy to complicate the Hue code with locks. Maybe there is another simpler way to fix it there or maybe do it in the connector itself?

**Comment by romainr** [comment]
If `poll` returns from data, one cleaner way might be to add the results in the handle `handle['result']`

**Comment by penggongkui** [comment]
> If `poll` returns from data, one cleaner way might be to add the results in the handle `handle['result']`

Sorry, I don't understand what means？Which line？

**Comment by romainr** [comment]
e.g.
If we have some result data here:
https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py#L316
we could add it to the query handle as `connection['results']` or `connection[`prefetched_results`].

And then in https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py#L353 we could check if there is some data already present in `connection['results']`?

Could also rename `connection` to `handle` to be more consistent https://github.com/cloudera/hue/blob/master/desktop/libs/notebook/src/notebook/connectors/sql_alchemy.py#L310

**Comment by penggongkui** [comment]
are you means real_result = fetchmany's data - connection['prefetched_results'] 

but connection['prefetched_results'] not always duplicate in fetchmany

**Comment by romainr** [comment]
If `connection['prefetched_results'] ` is empty this is fine, as now results will be added, maybe e.g.:

`connection.pop('prefetched_results', []) + connection['results']`

**Comment by penggongkui** [comment]
Add prefetched_result will make result duplicate twice. Because connection
result is already duplicate.

**Comment by romainr** [comment]
So why not remove the data rows in connection['results'] that are in connection.pop('prefetched_results', [])?

(could even be just removing the first len(connection.pop('prefetched_results', []))

**Comment by penggongkui** [comment]
prefetched result is not always duplicate in connection result
Case:
Prefetched: (1)
Connection: (1,1,2)

We don't know the real answer is (1,2) or (1,1,2)

**Comment by romainr** [comment]
And we can't guess that we need to drop just the first element in Connection as the size of Prefetched is one?

**Comment by penggongkui** [comment]
Yes

**Comment by sbbagal13** [comment]
@penggongkui Is this resolved or do we have any workaround for this ?  I am also facing similar issue with Trino

**Comment by penggongkui** [comment]
@sbbagal13 maybe use jdbc instead of sqlalchemy  is a workaround

**Comment by sbbagal13** [comment]
@penggongkui Thanks, if possible could you please suggest , how can I make trino connection with JDBC from hue configuration. As per document [connector](https://docs.gethue.com/administrator/configuration/connectors/#trino) gives on sqlalchemy config only

**Comment by penggongkui** [comment]
```
[[[presto]]]
      interface = jdbc
      name = Presto
      options = '{"url":"jdbc:presto://your-presto-address/hive/default","driver":"com.facebook.presto.jdbc.PrestoDriver","user":"","password":""}'
```
@sbbagal13 something like this

**Comment by sbbagal13** [comment]
Thanks @penggongkui, I will give a try JDBC connection with Trino along with impersonation

**Comment by deept-creditone** [comment]
Hi @penggongkui I tried using connecting Hue to Trino using jbdc connector however I am getting the following error:

decorators ERROR Error running autocomplete
Traceback (most recent call last):
File "/usr/share/hue/desktop/libs/notebook/src/notebook/decorators.py", line 119, in wrapper
return f(*args, **kwargs)
File "/usr/share/hue/desktop/libs/notebook/src/notebook/api.py", line 757, in autocomplete
autocomplete_data = get_api(request, snippet).autocomplete(snippet, database, table, column, nested, action)
File "/usr/share/hue/desktop/libs/notebook/src/notebook/models.py", line 586, in get_api
return ApiWrapper(request, snippet)
File "/usr/share/hue/desktop/libs/notebook/src/notebook/models.py", line 570, in __init__
self.api = _get_api(request, snippet)
File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/base.py", line 476, in get_api
from notebook.connectors.jdbc import JdbcApi
File "/usr/share/hue/desktop/libs/notebook/src/notebook/connectors/jdbc.py", line 51
raise QueryError, _('%s: is the DB Proxy server running?') % message, sys.exc_info()[2]
^
SyntaxError: invalid syntax

Could you please let me know the correct way to connect Hue to Trino using JBDC interface?

**Comment by sbbagal13** [comment]
@penggongkui , Our Trino connection is HTTPs enabled, I tried setting up connection as per your suggestion but its not working .. Below are my configurations, Kindly suggest if I am missing anything 
`  interpreters: |-
    [[[trino]]]
    name = Trino
    interface=jdbc
    options= '{"url":"jdbc:trino://<coordinator-host/rout>:443/cdls?SSL=true&SSLTrustStorePath=/etc/cert/ca_truststore.jks&SSLTrustStorePassword=xxxxxxx","driver":"io.trino.jdbc.TrinoDriver","user":"trino-user","password"="xxxxx", "impersonation_property": "true" }'` 

Connection end up with "unknown error" , I created sample java class and added all configs as above (except impersonation), connection works fine.

**Pull request closed without merging**
