### PR TITLE
[blog] Localized blogs published in May-June 2021 into Japanese

### PR DESCRIPTION
**Pull request by kawamon**
Hi Hue Team,
Congratulations on the release of Hue 4.10! I translated the hue blogs into Japanese.

## What changes were proposed in this pull request?

- Localized the blogs published in May-Jun into Japanese

## How was this patch tested?

- Verified on my browser using 'hugo serve'

Please let me know if you have any questions.

Regards,
--
Tatsuo

### CODE REVIEW

**Review by romainr — APPROVED** [review]
Nice!

**Comment by kawamon** [comment]
Hi Romain,

Thank you for merging my pull request!!

However, it seems these translated posts have not appeared in jp.gethue.com.
hue_blog_jp

https://jp.gethue.com/blog/hue-4-10-sql-scratchpad-component-rest-api-small-file-importer-slack-app/
hue_404


These posts are displayed well in my local environment.
image

Could you check it?
If the reason for this is from my side, please let me know.

Regards,
Tatsuo

**Comment by romainr** [comment]
Back online!

And I forgot that the JP website was not set to auto update itself yet!

It is good now: https://jp.gethue.com//posts/

Thanks a lot @kawamon !

**Comment by kawamon** [comment]
Hi Romain,

No problem! Thanks a lot!!

Regards,
--
Tatsuo

**Pull request merged**
