### PR TITLE
Fix a bug:about "file browser" -> "create" a "new file":

### PR DESCRIPTION
**Pull request by Xhxiong**
after judged same name,open the window again, emptied the contents of the file name.

### CODE REVIEW

**Comment by romainr** [comment]
Nice! Do you think you could just replace the tab by some spaces in the commit?
(that way it is indentated the same as the line $("#createFileModal").modal({ )

**Comment by Xhxiong** [comment]
About the first question,only use the line ($("#createFileModal").modal({ ),the window file name can not be empty.Replace the tab by a space looks like clear the window.

**Comment by romainr** [comment]
I just fixed the indentation and push the File Browser patch: https://github.com/cloudera/hue/commit/80e1a51f1061451d54f9404cbda4375154c6afcf

Could we follow-up in another pull request for the home page to keep it simple to track?

**Comment by romainr** [comment]
And when you have a chance, would you mind signing the online contributor form?

https://github.com/cloudera/hue/wiki/Ccla#online-form

Thanks again!

**Pull request closed without merging**
