### PR TITLE
[flink] Support Apache Flink 1.16 via its own SQL Gateway REST endpoints

### PR DESCRIPTION
**Pull request by agl29**
## What changes were proposed in this pull request?

-  Updated endpoints: requests and responses

## How was this patch tested?

- Locally via creating cluster

### CODE REVIEW

**Comment by grzegorz8** [comment]
@agl29 @JohanAhlen @Harshg999 May I asked why the PR was abandoned? Were there any problems with it? Thanks!

**Comment by grzegorz8** [comment]
Hey @agl29! I was testing your PR by applying it on release-4.11.0. Basically it works pretty fine, but there is one issue. Namely, when streaming query is running and results are available, it is not possible to cancel the query - red "Cancel" button is replaced with blue "Run" button. Do you happen to know how to fix that? Thanks in advance.

P.S. I saw that @romainr tried to address the issue in this PR: https://github.com/cloudera/hue/pull/1570

**Comment by ryanvanhuuksloot** [comment]
I'm also interested in this functionality

**Comment by ryanvanhuuksloot** [comment]
Amazing! I'd be happy to help / test. Feel free to tag me in a new PR.
Thanks

**Comment by grzegorz8** [comment]
@ryanvanhuuksloot I created a draft PR https://github.com/cloudera/hue/pull/3997. Feel free to test it. However, there are still some issues to be addressed. See my PR description and TODOs left in the code.

**Comment by ryanvanhuuksloot** [comment]
I've pivoted temporarily on other development tooling but I'll try it if we land on hue!

**Pull request closed without merging**
