### PR TITLE
[Django 3.0] ImportError: cannot import name 'six' from 'django.utils…

### PR DESCRIPTION
**Pull request by agl29**
…' due to line 13 in axes==4.5.4

## What changes were proposed in this pull request?

Django-axes upgraded from 4.5.4 to 5.13.0. and django-axes 5.13.0 depends on django-ipware<4 and >=3.
## How was this patch tested?

https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis
https://pypi.org/project/django-axes/

### CODE REVIEW

**Review by romainr — APPROVED** [review]
Just title message is unrelated?

**Comment by agl29** [comment]
> Just title message is unrelated?

this is the whole line ->ImportError: cannot import name 'six' from 'django.utils'  due to line 13 in axes==4.5.4. So half-line is in the description.

**Comment by romainr** [comment]
So was it django-axe depending on six from django?

**Comment by agl29** [comment]
> So was it django-axe depending on six from django? (which got removed)

yes, as you can see in ss (django-axes==4.5.4)
Screenshot 2021-02-16 at 11 45 57 PM

**Comment by romainr** [comment]
:+1: 
(just using above as commit message explains it more ;)

**Pull request merged**
