### PR TITLE
Fix the wrong syntax

### PR DESCRIPTION
**Pull request by HSunboy**
Fix the wrong syntax

### CODE REVIEW

**Comment by JohanAhlen** [comment]
Very nice! Before we can pull this in there are a couple of things that needs to be adjusted:

- Make sure the jasmine tests run (go to /jasmine) and you should adjust or add to sqlSpecCreate.js
- There's a bug in JISON, I've got a pull request waiting but in the meantime the files need to be generated using my fork, https://github.com/JohanAhlen/jison
- The parser can handle both Impala and Hive syntax, your change takes care of Hive but will break Impala (https://www.cloudera.com/documentation/enterprise/6/6.0/topics/impala_create_table.html) what you'd have to do is split the rules `WithSerdeproperties` and `OptionalWithSerdeproperties` into one for Impala and one for Hive, replace the existing ones with `OptionalImpalaWithSerdeProperties` and add `OptionalHiveWithSerdeProperties` where you moved it in your commit. As the rule is used for ALTER statements as well I'd add:
```
OptionalWithSerdeproperties
: OptionalImpalaWithSerdeproperties
| OptionalHiveWithSerdeproperties
;
```
- Underneath the rule where you removed `OptionalWithSerdeproperties` there are a bunch of if statements, taking care of autocomplete suggestions depending on which optional rules are present, with your current commit those would fail. If a rule is removed then the corresponding empty checks needs to be shifted.

If it's too much let me know and I can take care of it. :-)

**Comment by HSunboy** [comment]
@JohanAhlen thanks for your advice.
But I have a doubt, is it necessary to split the rules` WithSerdeproperties` and `OptionalWithSerdeproperties` into one for Impala and one for Hive?Because I can not see the difference between the two from the document.

**Comment by JohanAhlen** [comment]
For Impala the following would be allowed according to the docs:

`CREATE TABLE foo WITH SERDEPROPERTIES (...) STORED AS ...`

With your change, it would require  `<hive>STORED BY` in front of `WITH SERDEPROPERTIES`.

**Comment by HSunboy** [comment]
@JohanAhlen I have modified it according to your suggestion:D

**Comment by wing2fly** [comment]
@JohanAhlen and @HSunboy, can we have a Hue Jira to keep track of this issue? And add the Hue JIRA ID to the commit message?

**Comment by JohanAhlen** [comment]
Thanks @HSunboy!

Could you rename your commit to "HUE-8598 [autocomplete] Split the rules WithSerdeproperties and OptionalWithSerdeproperties into one for Impala and one for Hive"?

I will merge it in together with some related Impala changes later.

**Comment by HSunboy** [comment]
@JohanAhlen 👌

**Comment by JohanAhlen** [comment]
Added to master

**Comment by JohanAhlen** [comment]
@HSunboy would you mind putting your name in the legal contributor list if you haven't already?

https://github.com/cloudera/hue/wiki/Ccla#online-form

Thanks!

**Comment by HSunboy** [comment]
@JohanAhlen Ok, I have signed the CCLA.

**Pull request closed without merging**
